"use client";

import { FC } from "react";
import { useApplicationStore } from "@/store/use-application-store";
import { useDataStore } from "@/store/use-data-store";
import { ReactUnityEventParameter } from "react-unity-webgl/distribution/types/react-unity-event-parameters";

import Dialog from "../ui/dialog";
import { Button } from "../ui/button";
import { ScrollArea } from "../ui/scroll-area";
import { ChevronLeft } from "lucide-react";

import LevelCard from "./level-card";


interface LevelBrowserProps {
	sendMessage: (gameObjectName: string, methodName: string, parameter?: ReactUnityEventParameter) => void;
}

const LevelBrowser: FC<LevelBrowserProps> = ({ sendMessage }) => {

	const { levelBrowserActive, setLevelBrowserActive } = useApplicationStore();
	const { levels } = useDataStore();

	return (
		<Dialog
			open={levelBrowserActive}
			onOpenChange={setLevelBrowserActive}
			className="max-w-7xl min-h-[calc(100vh_-_10rem)]"
		>
			<div className="relative z-10 h-fulloutline-none">

				<div className="mb-8 flex items-center">
					<Button variant={"outline"} size={"icon"} className="shrink-0 mr-4" onClick={() => setLevelBrowserActive(false)}>
						<ChevronLeft />
					</Button>
					<h3 className="font-orbitron text-2xl tracking-wider">Level Browser</h3>
					<p className="ml-auto text-sm font-light text-muted-foreground">Play AI levels generated by the community.</p>
				</div>

				<ScrollArea className="h-[calc(100vh_-_18rem)] px-4">
					<div className="grid grid-cols-3 gap-4 w-full">
						{levels && levels.map((level, index) => (
							<LevelCard
								key={index}
								level={level}
								sendMessage={sendMessage}
							/>
						))}
					</div>
				</ScrollArea>

			</div>
		</Dialog>
	)
}

export default LevelBrowser;